// Generated by https://quicktype.io

export interface Forum {
    id:              number;
    nombre:          string;
    descripcion:     string;
    foto:            string;
    posicion:        number;
    id_categoria_fk: number;
}