// Generated by https://quicktype.io

export interface Topics {
    id:               number;
    titulo:           string;
    fecha:            string;
    tipo:             string;
    id_foro_fk:       number;
    nombre_foro:      string;
    descripcion_foro: string;
    foto:             string;
    id_usuario_fk:    string;
    escritor:         string;
    apodo_escritor:   string;
    borrado:          number;
}

export interface Topic {
    id:             number;
    titulo:         string;
    cuerpo:         string;
    fecha:          string;
    tipo:           string;
    id_foro_fk:     number;
    foto:           string;
    id_usuario_fk:  number;
    escritor:       string;
    apodo_escritor: string;
    foro:           string;
    foto_foro:      string;
    categoria:      string;
    pais:           string;
    ultima_visita:  string;
    borrado:          number;
}